presets:
  - name: cachelib
    image: ghcr.io/nguyenvukhang/uwuntu:12.5.1-devel-ubuntu22.04
    homedir: /home/appliedai
    user: appliedai
    shell: zsh
    volumes:
      - ["/media/appliedai/ssd_nvme/khang", "/home/appliedai/v"]
      - ["/media/appliedai/ssd_nvme", "/mnt/shared"]
      - ["/var/run/docker.sock", "/var/run/docker.sock"]
    ports:
      - [619, 22] # ssh
      - [12106, 6006] # TensorBoard
      - [12188, 8888] # Jupyter Notebook
    run_args:
      - --privileged
      - --runtime=nvidia
      - --gpus=all
      - --restart=always
