presets:
  - name: cachelib
    image: ghcr.io/nguyenvukhang/uwuntu:12.5.1-devel-ubuntu22.04
    homedir: /home/appliedai
    user: appliedai
    shell: zsh
    volumes: # [host, container]
      - ["/media/appliedai/ssd_nvme/khang", "/home/appliedai/v"]
      - ["/media/appliedai/ssd_nvme", "/mnt/shared"]
      - ["/var/run/docker.sock", "/var/run/docker.sock"]
    ports: # [host, container]
      - [9022, 22] # ssh
      - [9006, 6006] # TensorBoard
      - [9088, 8888] # Jupyter Notebook
    run_args:
      - --privileged
      - --runtime=nvidia
      - --gpus=all
      - --restart=always
