name: Build Docker Image

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build-apt-base:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cuda: 11.4.3
            os: ubuntu20.04
          - cuda: 12.2.2
            os: ubuntu20.04
          - cuda: 12.4.1
            os: ubuntu22.04
          - cuda: 12.5.0
            os: ubuntu22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo 'N=cuda:${{ matrix.cuda }}-devel-${{ matrix.os }}' >>$GITHUB_ENV
          echo 'T=cuda${{ matrix.cuda }}-${{ matrix.os }}' >>$GITHUB_ENV
      - name: Build base image
        run: docker build --build-arg="TAG=$N" -t apt-base-$T apt-base
      - name: Deploy
        run: |
          TAG=ghcr.io/$GITHUB_ACTOR/apt-base-$T
          VERSION="$(date "+%Y%m%d")"
          docker tag apt-base-$T $TAG:$VERSION
          docker tag apt-base-$T $TAG:latest
          docker images $TAG
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $TAG:$VERSION
          docker push $TAG:latest
      - name: Build user-facing image
        run: |
          docker build --build-arg="TAG=$T" -t uwuntu-$T .
      - name: Deploy
        run: |
          TAG="ghcr.io/$GITHUB_ACTOR/uwuntu-$T"
          VERSION="$(date "+%Y%m%d")"
          docker tag uwuntu-$T $TAG:$VERSION
          docker tag uwuntu-$T $TAG:latest
          docker images $TAG
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $TAG:$VERSION
          docker push $TAG:latest
