name: Build Docker Image

on:
  push:

permissions:
  contents: write
  packages: write

env:
  UPDATE_PACKAGES: false

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - cuda: 11.4.3
            os: ubuntu20.04
          - cuda: 12.2.2
            os: ubuntu20.04
          - cuda: 12.4.1
            os: ubuntu22.04
          - cuda: 12.5.0
            os: ubuntu22.04
          - cuda: 12.5.1
            os: ubuntu22.04
          - cuda: 12.6.2
            os: ubuntu22.04

    name: cuda${{ matrix.cuda }}+${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "T=${{ matrix.cuda }}-devel-${{ matrix.os }}" >>$GITHUB_ENV
          echo "D=$(date '+%Y%m%d')" >>$GITHUB_ENV
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      #  ///////////////////////////////////////////////////////////////////////
      # // Base image. Update apt packages from NVIDIA's image.
      - name: Build base image
        if: env.UPDATE_PACKAGES == 'true'
        run: |
          docker build --build-arg="TAG=$T" -t cuda:$T cuda

      - name: Deploy base image
        if: env.UPDATE_PACKAGES == 'true'
        run: |
          docker tag cuda:$T ghcr.io/$GITHUB_ACTOR/cuda:$T-$D
          docker tag cuda:$T ghcr.io/$GITHUB_ACTOR/cuda:$T

          docker push        ghcr.io/$GITHUB_ACTOR/cuda:$T-$D
          docker push        ghcr.io/$GITHUB_ACTOR/cuda:$T

      #  ///////////////////////////////////////////////////////////////////////
      # // User-facing image. The image with everything installed.
      - name: Build user-facing image
        run: |
          docker build --build-arg="TAG=$T" -t uwuntu:$T .

      - name: Deploy user-facing image
        run: |
          docker tag uwuntu:$T ghcr.io/$GITHUB_ACTOR/uwuntu:$T-$D
          docker tag uwuntu:$T ghcr.io/$GITHUB_ACTOR/uwuntu:$T

          docker push          ghcr.io/$GITHUB_ACTOR/uwuntu:$T-$D
          docker push          ghcr.io/$GITHUB_ACTOR/uwuntu:$T
